version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: librespeed_app
    environment:
      - PASSWORD=gimmeTheStats1337
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
      - DB_NAME=librespeed
      - DB_PASSWORD=Not4SecureProduction
      - DB_TYPE=mysql
      - DB_USERNAME=librespeed
      - EMAIL=test@example.com
      - ENABLE_ID_OBFUSCATION=true
      - MODE=frontend
      - REDACT_IP_ADDRESSES=false
      - TELEMETRY=true
      - WEBPORT=9000
    volumes:
      - ./docker/servers.json:/servers.json
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - my-proxy-network

  mysql:
    image: mysql
    container_name: librespeed_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Not4SecureProduction
      MYSQL_USER: librespeed
      MYSQL_PASSWORD: Not4SecureProduction
      MYSQL_DATABASE: librespeed
    volumes:
      - db_data:/var/lib/mysql
      - ./results/telemetry_mysql.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "3306:3306"
    networks:
      - my-proxy-network

  proxy:
    image: nginx:alpine
    container_name: librespeed_proxy
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-proxy-network

volumes:
  db_data:

networks:
  my-proxy-network:
    name: traefik_proxy
    external: true
